version: "3.9"
services:
  echo-server:
    build: .
    image: "romanowalex/echo-server:v2.0"
    container_name: echo-server
    environment:
      SPRING_PROFILES_ACTIVE: simple
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8080/manage/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.53.0-rc.0
    container_name: prometheus
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090"]
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 30s
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus/data"
    depends_on:
      echo-server:
        condition: service_healthy

  grafana:
    image: grafana/grafana:9.5.19
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "-spider", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 30s
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - type: bind
        source: ./grafana/
        target: /etc/grafana/provisioning/
    depends_on:
      prometheus:
        condition: service_healthy

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
