global:
  scrape_interval: 10s
  scrape_timeout: 8s
  evaluation_interval: 15s

scrape_configs:
  - job_name: echo-server
    metrics_path: /manage/prometheus
    static_configs:
      - targets: ["echo-server:8080"]
    honor_timestamps: true
    scheme: http
    follow_redirects: true
